# Generated by Django 5.2.15 on 2026-07-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_checks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('webhook', models.URLField()),
                ('header_key', models.CharField(blank=True, max_length=255)),
                ('header_value', models.CharField(blank=True, max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'webhook',
                'indexes': [models.Index(fields=['ip'], name='webhook_ip_ceae50_idx')],
            },
        ),
    ]
