# Generated by Django 5.2.15 on 2026-07-08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_checks', '0002_webhook'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcheckrequest',
            name='webhook',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='email_check_requests',
                to='email_checks.webhook',
            ),
        ),
    ]
